apiVersion: batch/v1
kind: Job
metadata:
  name: title1
spec:
  template:
    spec:
      containers:
        - name: title1
          image: python:latest
          command: [ "python", "-c" ]
          args: [ "print('Hello frавыфom the Kubernetes job')" ]
      restartPolicy: Never
  backoffLimit: 4
  